### ISSUE TITLE
Bayes factors for each variable and causal effect

### ISSUE THREAD

**Issue by joshchiou** [FinucaneLab/fine-mapping-inf#1]
Hi,
I've been running some comparisons between SuSiE-inf and the original SuSiE method and wanted to plot the results. Is it possible to extract the Bayes factors for each variant, for each casual effect (i.e. is there an equivalent of lbf_variable in SuSiE-inf)? I didn't see an equivalent in the SuSiE-inf output, but maybe I missed it. 
Thanks,
Josh

**Comment by joshchiou** [comment]
Never mind, I found it under the "logPIP" variable.

**Comment by cuiran** [comment]
Hi Josh,

Thank you for the question. You are correct that "logPIP" is the relevant variable. It should coincide with "lbf_variable" in SuSiE up to an additive constant. The constant may differ for each single effect.
