### ISSUE TITLE
Credible set generation seems to have some flaws

### ISSUE THREAD

**Issue by DSuveges** [FinucaneLab/fine-mapping-inf#6]
Hi Guys, I'm afraid, the [function](https://github.com/FinucaneLab/fine-mapping-inf/blob/7ff8f0f826f76f4fd726c4af6ad52a28d83e7e41/susieinf/susieinf.py#L213) that generates credible sets based of the vectors of the inclusion probabilities is not right:

There's this condition:
```python
    if np.min(np.abs(LDloc)) > purity:
      cred.append(sorted(list(credset)))
```

If ALL the abs(r) values reach the purity threshold, the logic keeps all elements, however, if at least one of r is "less pure", the credible set remains empty, as this condition doesn't have an `else` branch. I highly suspect this is not the intended behaviour.

**Comment by cuiran** [comment]
Thanks for the comment. This is indeed the intended behavior. We refer to the original SuSiE algorithm for justification. See the original [SuSiE code](https://github.com/stephenslab/susieR/blob/f63f9cb85fd78a6932ec9e00f1f4701d471eefba/R/susie_utils.R#L262C1-L262C13) for filtering credible set based on [purity threshold](https://github.com/stephenslab/susieR/blob/f63f9cb85fd78a6932ec9e00f1f4701d471eefba/R/susie_utils.R#L237). Also, see the [SuSiE manuscript](https://academic.oup.com/jrsssb/article/82/5/1273/7056114) section 3.2.2 for their description and justification for this credible set filtering behavior.

**Comment by DSuveges** [comment]
Oh, OK. Thank you so much for the clarification!
