### ISSUE TITLE
command to output .gz files

### ISSUE THREAD

**Issue by wuyangf7** [FinucaneLab/fine-mapping-inf#7]
May I ask how I can output .gz files in the new version? I tried --save-tsv and --save-npz, but not .gz files output any more.

**Comment by cuiran** [comment]
We added .bgz support in[ this commit](https://github.com/FinucaneLab/fine-mapping-inf/pull/4/commits/07bacdd3a8d9c96e29a472842be119edfe821025). Now instead of .gz the output files will have extension .bgz. I will update the corresponding Wiki and . Sorry about the confusion!
